### PR TITLE
Fix for #95

### LINKED ISSUE #95: Zygote and ChainRules are broken
Currently

```julia
using ComponentArrays, Zygote

f(a, sym) = getproperty(a, sym)
ca = ComponentArray(x = [1, 2], θ = [1.0, 100.0], deg = 2)
y, dy = Zygote.pullback(f, ca, Val{:x}())
dy(similar(y) .= 1)
```

fails with

```julia
BoundsError: attempt to access Tuple{Nothing, ComponentVector{Float64, Vector{Float64}, Tuple{Axis{(s = 1, m = 2:101)}}}} at index [3]

Stacktrace:
 [1] getindex
   @ ./tuple.jl:29 [inlined]
 [2] gradindex(x::Tuple{Nothing, ComponentVector{Float64, Vector{Float64}, Tuple{Axis{(s = 1, m = 2:101)}}}}, i::Int64)
   @ Zygote ~/.julia/packages/Zygote/6HN9x/src/compiler/reverse.jl:12
 [3] Pullback
   @ ./In[200]:1 [inlined]
 [4] (::typeof(∂(f)))(Δ::Vector{Float64})
   @ Zygote ./compiler/interface2.jl:0
 [5] (::Zygote.var"#41#42"{typeof(∂(_f))})(Δ::Vector{Float64})
   @ Zygote ~/.julia/packages/Zygote/6HN9x/src/compiler/interface.jl:41
 [6] top-level scope
   @ In[200]:3
 [7] eval
   @ ./boot.jl:360 [inlined]
 [8] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094
```

AFAIK the following occurs:
1. The rules in `src/compat/zygote.jl` is never hit, but instead we reach the rules in `src/compat/chainrulescore.jl`.
   - Interestingly `Zygote.pullback(getproperty, ca, Val{:x}())` actually works. I'm guessing this is because this hits the adjoint defined for `Zygote.literal_property` while in every other case you hit ChainRules's impl.
2. The rules defined in `src/compat/chainrulescore.jl` seem incorrect, as they're missing the `NoTangent` for the key used in `getproperty`, hence the `getindex` error above.

AFAIK this also means that `src/compat/zygote.jl` can just be removed.

Also, is there a reason why ChainRulesCore.jl shouldn't be a dependency of ComponentArrays.jl? This would allow specifying compat-bounds and thus avoiding impls "silently" going out of date, as seems to have happened above.

### PR DESCRIPTION
**Pull request by torfjelde**
This PR fixes #95 and removes the now redundant Zygote.jl-specific rules in favour of ChainRules.jl-only.

In the process I also improved the testing for AD a bit and noticed that ReverseDiff.jl will silently compute the wrong gradient when using `getindex`. I've currently just marked these cases as broken.

Also, IMO ChainRulesCore.jl should just be a direct dependency so compat-bounds can be added. #95 likely would have been avoided if that was the case, though I realize at the time of impl this might not have made as much sense.

EDIT: _Also_, is there a reason why Manifest.toml is used in `test/`? Maybe this should also be removed in favour of compat-bounds in `test/Project.toml`?

### CODE REVIEW

File: test/autodiff_tests.jl [hunk 1]
```diff
@@ -1,29 +1,32 @@
...
-        reverse = ReverseDiff.gradient(ca -> F_prop(ca), ca).x,
-        # zygote = Zygote.gradient(ca -> F(ca), ca)[1].x,
-    )
-end
+    forward = ForwardDiff.gradient(ca -> F_(ca), ca).x
+    @test forward ≈ truth
+
+    reverse = ReverseDiff.gradient(ca -> F_(ca), ca).x
+    if F_ in (F_idx_val, F_idx_sym)
+        @test_broken reverse ≈ truth
```
Comment (torfjelde) [inline test/autodiff_tests.jl:25]: Produces a zero-vector rather than `truth`. Guessing there's something wrong with `src/compat/reversediff.jl` but I haven't investigated this further.

**Comment by jonniedie** [comment]
Thanks for this!

I'm glad you caught that ReverseDiff issue. ReverseDiff support is pretty new for ComponentArrays, so it will be good to have better tests for that. I'll figure out what's going wrong with it.

Yes, I agree that ChainRulesCore should be a direct dependency.  I've been meaning to move some of the low-dependency packages like this out of Requires and into direct dependencies.

No, there's no reason Manifest is being used in `test/`. That can change to using compat bounds.

Also, I'll try to track down why this failing for v1.2 and nightly. I guess it's not a huge deal if we need to drop support for v1.2, but ideally I'd like to keep it if at all possible.

**Comment by jonniedie** [comment]
Oh, nevermind on the v1.2 thing. That's only failing now because the Zygote tests (which were broken before on v1.2) are running again. I'll put a `@test_broken` for v1.2 so we can keep this.

**Comment by jonniedie** [comment]
Also, the nightly thing looks like it has to do with [this](https://github.com/FluxML/IRTools.jl/commit/a02baf10c2fc58081357d386909b8aaf139bed2a#diff-fc037e4d24177201db17d86b999cedf6f381fec1182709aa2eab4c5497cb14f2R5), so I'm not worried about that either.

**Comment by torfjelde** [comment]
Good stuff!:)
